### ISSUE TITLE
Git install error

### ISSUE THREAD

**Issue by DuaneDuan** [nocodb/nocodb-seed#4]
CentOS: 7.7 64bit
nodejs: 16.14.0
npm: 8.3.1

after installed,
get the error when run: Cannot find module 'nocodb' 
 
` npm run start `

Error: 
 ```
 help@1.0.0 start
  node index.js

node:internal/modules/cjs/loader:933
  const err = new Error(message);
              ^

Error: Cannot find module 'nocodb'
Require stack:
- /root/nocodb/nocodb-seed/index.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at /root/nocodb/nocodb-seed/index.js:3:20
    at Object.<anonymous> (/root/nocodb/nocodb-seed/index.js:7:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1155:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/root/nocodb/nocodb-seed/index.js' ]
}
```

**Comment by ampxtreme** [comment]
+1
